#
# FEDGParser Library
#
# Copyright 2010-2013 Fabric Engine Inc. All rights reserved.
#

import os, sys, platform
Import('samplesEnv', 'installRoot')
env = samplesEnv.Clone()

appName = os.path.split(Dir('.').abspath)[1].partition('_')[2]
program = env.Program(appName, Glob("*.cpp"))

installDir = os.path.join(installRoot, 'Samples', 'FabricSpliceAPI')
installedProgram = env.Install(installDir, program)
Return('installedProgram')

